# Generated by Django 6.0.7 on 2026-08-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email de bienvenue envoyé'),
        ),
    ]
