# Generated by Django 6.0.7 on 2026-07-30 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flutterwave_transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID transaction Flutterwave'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Réduction (%)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('flutterwave', 'Mobile Money (Flutterwave)'), ('free', 'Gratuit')], default='stripe', max_length=20, verbose_name='Moyen de paiement'),
        ),
    ]
