# Generated by Django 6.0.7 on 2026-07-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_flutterwave_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fedapay_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Token de paiement FedaPay'),
        ),
        migrations.AddField(
            model_name='order',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID transaction FedaPay'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('flutterwave', 'Mobile Money (Flutterwave)'), ('fedapay', 'Mobile Money (FedaPay)'), ('free', 'Gratuit')], default='stripe', max_length=20, verbose_name='Moyen de paiement'),
        ),
    ]
