# Generated by Django 6.0.7 on 2026-07-29 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('points_required', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Points requis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loyalty/rewards/%Y/%m/', verbose_name='Image')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock (0 = illimité)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Récompense',
                'verbose_name_plural': 'Récompenses',
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Points dépensés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyreward', verbose_name='Récompense')),
            ],
            options={
                'verbose_name': 'Échange de récompense',
                'verbose_name_plural': 'Échanges de récompenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('transaction_type', models.CharField(choices=[('earned', 'Gagnés'), ('redeemed', 'Échangés'), ('expired', 'Expirés'), ('adjusted', 'Ajustés')], max_length=20, verbose_name='Type de transaction')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction de fidélité',
                'verbose_name_plural': 'Transactions de fidélité',
                'ordering': ['-created_at'],
            },
        ),
    ]
